const ContractActionTypes = {
  LOAD_CONTRACTS: 'LOAD_CONTRACTS',

  CREATE_USER_START: 'CREATE_USER_START',
  CREATE_USER_END: 'CREATE_USER_END',

  GET_LOGGED_IN_USER_START: 'GET_LOGGED_IN_USER_START',
  GET_LOGGED_IN_USER_SUCCESS: 'GET_LOGGED_IN_USER_SUCCESS',

  GET_USER_START: 'GET_USER_START',
  GET_USER_END: 'GET_USER_END',

  CREATE_TWEET_START: 'CREATE_TWEET_START',
  CREATE_TWEET_END: 'CREATE_TWEET_END',

  GET_TWEET_START: 'GET_TWEET_START',
  GET_TWEET_END: 'GET_TWEET_END',

  GET_ALL_TWEETS_START: 'GET_ALL_TWEETS_START',
  GET_ALL_TWEETS_END: 'GET_ALL_TWEETS_END'
};

export default ContractActionTypes;
